<!--
SPDX-FileCopyrightText: Copyright (c) 2026, OPC Federation AISBL
SPDX-License-Identifier: MIT
-->

<xs:schema targetNamespace="http://opcfoundation.org/UA/PlasticsRubber/Dosing/Types.xsd" xmlns:tns="http://opcfoundation.org/UA/PlasticsRubber/Dosing/Types.xsd" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ua="http://opcfoundation.org/UA/2008/02/Types.xsd">
    <xs:import namespace="http://opcfoundation.org/UA/2008/02/Types.xsd"/>
    <xs:simpleType name="ComponentStateEnumeration">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Off_0"/>
            <xs:enumeration value="Ready_1"/>
            <xs:enumeration value="Dosing_2"/>
            <xs:enumeration value="Calibration_3"/>
            <xs:enumeration value="Error_4"/>
            <xs:enumeration value="Cleaning_5"/>
            <xs:enumeration value="Purging_6"/>
            <xs:enumeration value="Priming_7"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element type="tns:ComponentStateEnumeration" name="ComponentStateEnumeration"/>
    <xs:complexType name="ListOfComponentStateEnumeration">
        <xs:sequence>
            <xs:element type="tns:ComponentStateEnumeration" minOccurs="0" nillable="true" maxOccurs="unbounded" name="ComponentStateEnumeration"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element type="tns:ListOfComponentStateEnumeration" nillable="true" name="ListOfComponentStateEnumeration"/>
    <xs:simpleType name="DosingModeEnumeration">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ONLY_CONVEYING_0"/>
            <xs:enumeration value="VOLUMETRIC_1"/>
            <xs:enumeration value="GRAVIMETRIC_2"/>
            <xs:enumeration value="OTHER_3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element type="tns:DosingModeEnumeration" name="DosingModeEnumeration"/>
    <xs:complexType name="ListOfDosingModeEnumeration">
        <xs:sequence>
            <xs:element type="tns:DosingModeEnumeration" minOccurs="0" nillable="true" maxOccurs="unbounded" name="DosingModeEnumeration"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element type="tns:ListOfDosingModeEnumeration" nillable="true" name="ListOfDosingModeEnumeration"/>
</xs:schema>
