export const NS = 'urn:opcfoundation.org:2024-01:DemoModel';

export class BrowseNames {
   static readonly Amber_Placeholder: string = '<Amber>'
   static readonly BlueType: string = 'BlueType'
   static readonly BrightnessType: string = 'BrightnessType'
   static readonly DemoModel_BinarySchema: string = 'DemoModel'
   static readonly DemoModel_XmlSchema: string = 'DemoModel'
   static readonly EnumUnderscoreTest: string = 'EnumUnderscoreTest'
   static readonly ExtendedWorkOrderType: string = 'ExtendedWorkOrderType'
   static readonly FinalWorkOrderType: string = 'FinalWorkOrderType'
   static readonly Green_Placeholder: string = '<Green>'
   static readonly HeaterStatus: string = 'HeaterStatus'
   static readonly Indigo_Placeholder: string = '<Indigo>'
   static readonly PenultimateWorkOrderType: string = 'PenultimateWorkOrderType'
   static readonly Person: string = 'Person'
   static readonly Picture: string = 'Picture'
   static readonly PictureType: string = 'PictureType'
   static readonly Pink_Placeholder: string = '<Pink>'
   static readonly Red: string = 'Red'
   static readonly RestrictedObjectType: string = 'RestrictedObjectType'
   static readonly RestrictedVariableType: string = 'RestrictedVariableType'
   static readonly SampleStructureAllowSubtypes: string = 'SampleStructureAllowSubtypes'
   static readonly SampleStructureWithOptionalFields: string = 'SampleStructureWithOptionalFields'
   static readonly SampleUnion: string = 'SampleUnion'
   static readonly SampleUnionAllowSubtypes: string = 'SampleUnionAllowSubtypes'
   static readonly Seeker: string = 'Seeker'
   static readonly Shade: string = 'Shade'
   static readonly Student: string = 'Student'
   static readonly Test_Error: string = 'Test_Error'
   static readonly Test_ErrorComponent: string = 'Test_ErrorComponent'
   static readonly TestObject: string = 'TestObject'
   static readonly Vector: string = 'Vector'
   static readonly WithTwoDimensionalVariableType: string = 'WithTwoDimensionalVariableType'
   static readonly WorkOrderStatusType: string = 'WorkOrderStatusType'
   static readonly WorkOrderType: string = 'WorkOrderType'
   static readonly X: string = 'X'
   static readonly Y: string = 'Y'
   static readonly Yellow: string = 'Yellow'
   static readonly YellowThing: string = 'YellowThing'
   static readonly YellowType: string = 'YellowType'
   static readonly Z: string = 'Z'
}

export class DataTypeIds {
    static readonly EnumUnderscoreTest: string = 'nsu=' + NS + ';i=68'
    static readonly HeaterStatus: string = 'nsu=' + NS + ';i=1'
    static readonly Vector: string = 'nsu=' + NS + ';i=3'
    static readonly WorkOrderStatusType: string = 'nsu=' + NS + ';i=4'
    static readonly WorkOrderType: string = 'nsu=' + NS + ';i=5'
    static readonly ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=322'
    static readonly PenultimateWorkOrderType: string = 'nsu=' + NS + ';i=354'
    static readonly FinalWorkOrderType: string = 'nsu=' + NS + ';i=332'
    static readonly SampleUnion: string = 'nsu=' + NS + ';i=41'
    static readonly SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=42'
    static readonly SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=43'
    static readonly SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=44'
    static readonly Person: string = 'nsu=' + NS + ';i=222'
    static readonly Student: string = 'nsu=' + NS + ';i=223'
}

export class MethodIds {
    static readonly RestrictedObjectType_BlueType: string = 'nsu=' + NS + ';i=342'
    static readonly TestObject_BlueType: string = 'nsu=' + NS + ';i=343'
}

export class ObjectIds {
    static readonly Seeker: string = 'nsu=' + NS + ';i=95'
    static readonly TestObject: string = 'nsu=' + NS + ';i=128'
    static readonly Test_Error: string = 'nsu=' + NS + ';i=93'
    static readonly Test_ErrorComponent: string = 'nsu=' + NS + ';i=94'
    static readonly BrightnessType_Amber_Placeholder: string = 'nsu=' + NS + ';i=365'
    static readonly BrightnessType_Green_Placeholder: string = 'nsu=' + NS + ';i=367'
    static readonly PictureType_Indigo_Placeholder: string = 'nsu=' + NS + ';i=380'
    static readonly Picture: string = 'nsu=' + NS + ';i=351'
    static readonly Vector_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=21'
    static readonly WorkOrderStatusType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=22'
    static readonly WorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=23'
    static readonly ExtendedWorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=323'
    static readonly PenultimateWorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=355'
    static readonly FinalWorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=333'
    static readonly SampleUnion_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=45'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=46'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=47'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=48'
    static readonly Person_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=224'
    static readonly Student_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=225'
    static readonly Vector_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=6'
    static readonly WorkOrderStatusType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=7'
    static readonly WorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=8'
    static readonly ExtendedWorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=327'
    static readonly PenultimateWorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=359'
    static readonly FinalWorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=337'
    static readonly SampleUnion_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=62'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=63'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=64'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=65'
    static readonly Person_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=232'
    static readonly Student_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=233'
    static readonly Vector_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=79'
    static readonly WorkOrderStatusType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=80'
    static readonly WorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=81'
    static readonly ExtendedWorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=331'
    static readonly PenultimateWorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=363'
    static readonly FinalWorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=341'
    static readonly SampleUnion_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=82'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=83'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=84'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=85'
    static readonly Person_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=240'
    static readonly Student_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=241'
}

export class ObjectTypeIds {
    static readonly RestrictedObjectType: string = 'nsu=' + NS + ';i=124'
    static readonly BrightnessType: string = 'nsu=' + NS + ';i=364'
    static readonly PictureType: string = 'nsu=' + NS + ';i=348'
    static readonly WithTwoDimensionalVariableType: string = 'nsu=' + NS + ';i=120'
}

export class VariableIds {
    static readonly Seeker_Identities: string = 'nsu=' + NS + ';i=10'
    static readonly Seeker_AddIdentity_InputArguments: string = 'nsu=' + NS + ';i=25'
    static readonly Seeker_RemoveIdentity_InputArguments: string = 'nsu=' + NS + ';i=29'
    static readonly Seeker_AddApplication_InputArguments: string = 'nsu=' + NS + ';i=32'
    static readonly Seeker_RemoveApplication_InputArguments: string = 'nsu=' + NS + ';i=35'
    static readonly Seeker_AddEndpoint_InputArguments: string = 'nsu=' + NS + ';i=52'
    static readonly Seeker_RemoveEndpoint_InputArguments: string = 'nsu=' + NS + ';i=55'
    static readonly EnumUnderscoreTest_EnumValues: string = 'nsu=' + NS + ';i=69'
    static readonly RestrictedVariableType_Yellow: string = 'nsu=' + NS + ';i=123'
    static readonly RestrictedVariableType_X: string = 'nsu=' + NS + ';i=210'
    static readonly RestrictedVariableType_Y: string = 'nsu=' + NS + ';i=211'
    static readonly RestrictedVariableType_Z: string = 'nsu=' + NS + ';i=212'
    static readonly RestrictedObjectType_Red: string = 'nsu=' + NS + ';i=125'
    static readonly RestrictedObjectType_Red_Yellow: string = 'nsu=' + NS + ';i=57'
    static readonly RestrictedObjectType_Red_X: string = 'nsu=' + NS + ';i=213'
    static readonly RestrictedObjectType_Red_Y: string = 'nsu=' + NS + ';i=214'
    static readonly RestrictedObjectType_Red_Z: string = 'nsu=' + NS + ';i=215'
    static readonly RestrictedObjectType_Pink_Placeholder: string = 'nsu=' + NS + ';i=132'
    static readonly RestrictedObjectType_Pink_Placeholder_Yellow: string = 'nsu=' + NS + ';i=58'
    static readonly RestrictedObjectType_Pink_Placeholder_X: string = 'nsu=' + NS + ';i=216'
    static readonly RestrictedObjectType_Pink_Placeholder_Y: string = 'nsu=' + NS + ';i=217'
    static readonly RestrictedObjectType_Pink_Placeholder_Z: string = 'nsu=' + NS + ';i=218'
    static readonly TestObject_Red: string = 'nsu=' + NS + ';i=60'
    static readonly TestObject_Red_Yellow: string = 'nsu=' + NS + ';i=61'
    static readonly TestObject_Red_X: string = 'nsu=' + NS + ';i=219'
    static readonly TestObject_Red_Y: string = 'nsu=' + NS + ';i=220'
    static readonly TestObject_Red_Z: string = 'nsu=' + NS + ';i=221'
    static readonly YellowType_Shade: string = 'nsu=' + NS + ';i=346'
    static readonly YellowType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=347'
    static readonly BrightnessType_Amber_Placeholder_StateNumber: string = 'nsu=' + NS + ';i=366'
    static readonly BrightnessType_Green_Placeholder_CurrentState: string = 'nsu=' + NS + ';i=368'
    static readonly BrightnessType_Green_Placeholder_CurrentState_Id: string = 'nsu=' + NS + ';i=369'
    static readonly BrightnessType_Green_Placeholder_LastTransition_Id: string = 'nsu=' + NS + ';i=374'
    static readonly PictureType_YellowThing: string = 'nsu=' + NS + ';i=349'
    static readonly PictureType_YellowThing_Shade: string = 'nsu=' + NS + ';i=350'
    static readonly Picture_YellowThing: string = 'nsu=' + NS + ';i=352'
    static readonly Picture_YellowThing_Shade: string = 'nsu=' + NS + ';i=353'
    static readonly HeaterStatus_EnumStrings: string = 'nsu=' + NS + ';i=2'
    static readonly WithTwoDimensionalVariableType_X: string = 'nsu=' + NS + ';i=121'
    static readonly DemoModel_BinarySchema: string = 'nsu=' + NS + ';i=24'
    static readonly DemoModel_BinarySchema_NamespaceUri: string = 'nsu=' + NS + ';i=26'
    static readonly DemoModel_BinarySchema_Deprecated: string = 'nsu=' + NS + ';i=49'
    static readonly DemoModel_BinarySchema_Vector: string = 'nsu=' + NS + ';i=27'
    static readonly DemoModel_BinarySchema_WorkOrderStatusType: string = 'nsu=' + NS + ';i=30'
    static readonly DemoModel_BinarySchema_WorkOrderType: string = 'nsu=' + NS + ';i=33'
    static readonly DemoModel_BinarySchema_ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=324'
    static readonly DemoModel_BinarySchema_PenultimateWorkOrderType: string = 'nsu=' + NS + ';i=356'
    static readonly DemoModel_BinarySchema_FinalWorkOrderType: string = 'nsu=' + NS + ';i=334'
    static readonly DemoModel_BinarySchema_SampleUnion: string = 'nsu=' + NS + ';i=50'
    static readonly DemoModel_BinarySchema_SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=53'
    static readonly DemoModel_BinarySchema_SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=56'
    static readonly DemoModel_BinarySchema_SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=59'
    static readonly DemoModel_BinarySchema_Person: string = 'nsu=' + NS + ';i=226'
    static readonly DemoModel_BinarySchema_Student: string = 'nsu=' + NS + ';i=229'
    static readonly DemoModel_XmlSchema: string = 'nsu=' + NS + ';i=9'
    static readonly DemoModel_XmlSchema_NamespaceUri: string = 'nsu=' + NS + ';i=11'
    static readonly DemoModel_XmlSchema_Deprecated: string = 'nsu=' + NS + ';i=66'
    static readonly DemoModel_XmlSchema_Vector: string = 'nsu=' + NS + ';i=12'
    static readonly DemoModel_XmlSchema_WorkOrderStatusType: string = 'nsu=' + NS + ';i=15'
    static readonly DemoModel_XmlSchema_WorkOrderType: string = 'nsu=' + NS + ';i=18'
    static readonly DemoModel_XmlSchema_ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=328'
    static readonly DemoModel_XmlSchema_PenultimateWorkOrderType: string = 'nsu=' + NS + ';i=360'
    static readonly DemoModel_XmlSchema_FinalWorkOrderType: string = 'nsu=' + NS + ';i=338'
    static readonly DemoModel_XmlSchema_SampleUnion: string = 'nsu=' + NS + ';i=67'
    static readonly DemoModel_XmlSchema_SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=70'
    static readonly DemoModel_XmlSchema_SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=73'
    static readonly DemoModel_XmlSchema_SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=76'
    static readonly DemoModel_XmlSchema_Person: string = 'nsu=' + NS + ';i=234'
    static readonly DemoModel_XmlSchema_Student: string = 'nsu=' + NS + ';i=237'
}

export class VariableTypeIds {
    static readonly RestrictedVariableType: string = 'nsu=' + NS + ';i=122'
    static readonly YellowType: string = 'nsu=' + NS + ';i=345'
}
