export const NS = 'urn:opcfoundation.org:2024-01:DemoModel';

export const BrowseNames = Object.freeze({
   Amber_Placeholder: '<Amber>',
   BlueType: 'BlueType',
   BrightnessType: 'BrightnessType',
   DemoModel_BinarySchema: 'DemoModel',
   DemoModel_XmlSchema: 'DemoModel',
   EnumUnderscoreTest: 'EnumUnderscoreTest',
   ExtendedWorkOrderType: 'ExtendedWorkOrderType',
   FinalWorkOrderType: 'FinalWorkOrderType',
   Green_Placeholder: '<Green>',
   HeaterStatus: 'HeaterStatus',
   Indigo_Placeholder: '<Indigo>',
   PenultimateWorkOrderType: 'PenultimateWorkOrderType',
   Person: 'Person',
   Picture: 'Picture',
   PictureType: 'PictureType',
   Pink_Placeholder: '<Pink>',
   Red: 'Red',
   RestrictedObjectType: 'RestrictedObjectType',
   RestrictedVariableType: 'RestrictedVariableType',
   SampleStructureAllowSubtypes: 'SampleStructureAllowSubtypes',
   SampleStructureWithOptionalFields: 'SampleStructureWithOptionalFields',
   SampleUnion: 'SampleUnion',
   SampleUnionAllowSubtypes: 'SampleUnionAllowSubtypes',
   Seeker: 'Seeker',
   Shade: 'Shade',
   Student: 'Student',
   Test_Error: 'Test_Error',
   Test_ErrorComponent: 'Test_ErrorComponent',
   TestObject: 'TestObject',
   Vector: 'Vector',
   WithTwoDimensionalVariableType: 'WithTwoDimensionalVariableType',
   WorkOrderStatusType: 'WorkOrderStatusType',
   WorkOrderType: 'WorkOrderType',
   X: 'X',
   Y: 'Y',
   Yellow: 'Yellow',
   YellowThing: 'YellowThing',
   YellowType: 'YellowType',
   Z: 'Z',
});

export const DataTypeIds = Object.freeze({
   EnumUnderscoreTest: 'nsu=' + NS + ';i=68',
   HeaterStatus: 'nsu=' + NS + ';i=1',
   Vector: 'nsu=' + NS + ';i=3',
   WorkOrderStatusType: 'nsu=' + NS + ';i=4',
   WorkOrderType: 'nsu=' + NS + ';i=5',
   ExtendedWorkOrderType: 'nsu=' + NS + ';i=322',
   PenultimateWorkOrderType: 'nsu=' + NS + ';i=354',
   FinalWorkOrderType: 'nsu=' + NS + ';i=332',
   SampleUnion: 'nsu=' + NS + ';i=41',
   SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=42',
   SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=43',
   SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=44',
   Person: 'nsu=' + NS + ';i=222',
   Student: 'nsu=' + NS + ';i=223',
});

export const MethodIds = Object.freeze({
   RestrictedObjectType_BlueType: 'nsu=' + NS + ';i=342',
   TestObject_BlueType: 'nsu=' + NS + ';i=343',
});

export const ObjectIds = Object.freeze({
   Seeker: 'nsu=' + NS + ';i=95',
   TestObject: 'nsu=' + NS + ';i=128',
   Test_Error: 'nsu=' + NS + ';i=93',
   Test_ErrorComponent: 'nsu=' + NS + ';i=94',
   BrightnessType_Amber_Placeholder: 'nsu=' + NS + ';i=365',
   BrightnessType_Green_Placeholder: 'nsu=' + NS + ';i=367',
   PictureType_Indigo_Placeholder: 'nsu=' + NS + ';i=380',
   Picture: 'nsu=' + NS + ';i=351',
   Vector_Encoding_DefaultBinary: 'nsu=' + NS + ';i=21',
   WorkOrderStatusType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=22',
   WorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=23',
   ExtendedWorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=323',
   PenultimateWorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=355',
   FinalWorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=333',
   SampleUnion_Encoding_DefaultBinary: 'nsu=' + NS + ';i=45',
   SampleStructureWithOptionalFields_Encoding_DefaultBinary: 'nsu=' + NS + ';i=46',
   SampleUnionAllowSubtypes_Encoding_DefaultBinary: 'nsu=' + NS + ';i=47',
   SampleStructureAllowSubtypes_Encoding_DefaultBinary: 'nsu=' + NS + ';i=48',
   Person_Encoding_DefaultBinary: 'nsu=' + NS + ';i=224',
   Student_Encoding_DefaultBinary: 'nsu=' + NS + ';i=225',
   Vector_Encoding_DefaultXml: 'nsu=' + NS + ';i=6',
   WorkOrderStatusType_Encoding_DefaultXml: 'nsu=' + NS + ';i=7',
   WorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=8',
   ExtendedWorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=327',
   PenultimateWorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=359',
   FinalWorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=337',
   SampleUnion_Encoding_DefaultXml: 'nsu=' + NS + ';i=62',
   SampleStructureWithOptionalFields_Encoding_DefaultXml: 'nsu=' + NS + ';i=63',
   SampleUnionAllowSubtypes_Encoding_DefaultXml: 'nsu=' + NS + ';i=64',
   SampleStructureAllowSubtypes_Encoding_DefaultXml: 'nsu=' + NS + ';i=65',
   Person_Encoding_DefaultXml: 'nsu=' + NS + ';i=232',
   Student_Encoding_DefaultXml: 'nsu=' + NS + ';i=233',
   Vector_Encoding_DefaultJson: 'nsu=' + NS + ';i=79',
   WorkOrderStatusType_Encoding_DefaultJson: 'nsu=' + NS + ';i=80',
   WorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=81',
   ExtendedWorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=331',
   PenultimateWorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=363',
   FinalWorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=341',
   SampleUnion_Encoding_DefaultJson: 'nsu=' + NS + ';i=82',
   SampleStructureWithOptionalFields_Encoding_DefaultJson: 'nsu=' + NS + ';i=83',
   SampleUnionAllowSubtypes_Encoding_DefaultJson: 'nsu=' + NS + ';i=84',
   SampleStructureAllowSubtypes_Encoding_DefaultJson: 'nsu=' + NS + ';i=85',
   Person_Encoding_DefaultJson: 'nsu=' + NS + ';i=240',
   Student_Encoding_DefaultJson: 'nsu=' + NS + ';i=241',
});

export const ObjectTypeIds = Object.freeze({
   RestrictedObjectType: 'nsu=' + NS + ';i=124',
   BrightnessType: 'nsu=' + NS + ';i=364',
   PictureType: 'nsu=' + NS + ';i=348',
   WithTwoDimensionalVariableType: 'nsu=' + NS + ';i=120',
});

export const VariableIds = Object.freeze({
   Seeker_Identities: 'nsu=' + NS + ';i=10',
   Seeker_AddIdentity_InputArguments: 'nsu=' + NS + ';i=25',
   Seeker_RemoveIdentity_InputArguments: 'nsu=' + NS + ';i=29',
   Seeker_AddApplication_InputArguments: 'nsu=' + NS + ';i=32',
   Seeker_RemoveApplication_InputArguments: 'nsu=' + NS + ';i=35',
   Seeker_AddEndpoint_InputArguments: 'nsu=' + NS + ';i=52',
   Seeker_RemoveEndpoint_InputArguments: 'nsu=' + NS + ';i=55',
   EnumUnderscoreTest_EnumValues: 'nsu=' + NS + ';i=69',
   RestrictedVariableType_Yellow: 'nsu=' + NS + ';i=123',
   RestrictedVariableType_X: 'nsu=' + NS + ';i=210',
   RestrictedVariableType_Y: 'nsu=' + NS + ';i=211',
   RestrictedVariableType_Z: 'nsu=' + NS + ';i=212',
   RestrictedObjectType_Red: 'nsu=' + NS + ';i=125',
   RestrictedObjectType_Red_Yellow: 'nsu=' + NS + ';i=57',
   RestrictedObjectType_Red_X: 'nsu=' + NS + ';i=213',
   RestrictedObjectType_Red_Y: 'nsu=' + NS + ';i=214',
   RestrictedObjectType_Red_Z: 'nsu=' + NS + ';i=215',
   RestrictedObjectType_Pink_Placeholder: 'nsu=' + NS + ';i=132',
   RestrictedObjectType_Pink_Placeholder_Yellow: 'nsu=' + NS + ';i=58',
   RestrictedObjectType_Pink_Placeholder_X: 'nsu=' + NS + ';i=216',
   RestrictedObjectType_Pink_Placeholder_Y: 'nsu=' + NS + ';i=217',
   RestrictedObjectType_Pink_Placeholder_Z: 'nsu=' + NS + ';i=218',
   TestObject_Red: 'nsu=' + NS + ';i=60',
   TestObject_Red_Yellow: 'nsu=' + NS + ';i=61',
   TestObject_Red_X: 'nsu=' + NS + ';i=219',
   TestObject_Red_Y: 'nsu=' + NS + ';i=220',
   TestObject_Red_Z: 'nsu=' + NS + ';i=221',
   YellowType_Shade: 'nsu=' + NS + ';i=346',
   YellowType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=347',
   BrightnessType_Amber_Placeholder_StateNumber: 'nsu=' + NS + ';i=366',
   BrightnessType_Green_Placeholder_CurrentState: 'nsu=' + NS + ';i=368',
   BrightnessType_Green_Placeholder_CurrentState_Id: 'nsu=' + NS + ';i=369',
   BrightnessType_Green_Placeholder_LastTransition_Id: 'nsu=' + NS + ';i=374',
   PictureType_YellowThing: 'nsu=' + NS + ';i=349',
   PictureType_YellowThing_Shade: 'nsu=' + NS + ';i=350',
   Picture_YellowThing: 'nsu=' + NS + ';i=352',
   Picture_YellowThing_Shade: 'nsu=' + NS + ';i=353',
   HeaterStatus_EnumStrings: 'nsu=' + NS + ';i=2',
   WithTwoDimensionalVariableType_X: 'nsu=' + NS + ';i=121',
   DemoModel_BinarySchema: 'nsu=' + NS + ';i=24',
   DemoModel_BinarySchema_NamespaceUri: 'nsu=' + NS + ';i=26',
   DemoModel_BinarySchema_Deprecated: 'nsu=' + NS + ';i=49',
   DemoModel_BinarySchema_Vector: 'nsu=' + NS + ';i=27',
   DemoModel_BinarySchema_WorkOrderStatusType: 'nsu=' + NS + ';i=30',
   DemoModel_BinarySchema_WorkOrderType: 'nsu=' + NS + ';i=33',
   DemoModel_BinarySchema_ExtendedWorkOrderType: 'nsu=' + NS + ';i=324',
   DemoModel_BinarySchema_PenultimateWorkOrderType: 'nsu=' + NS + ';i=356',
   DemoModel_BinarySchema_FinalWorkOrderType: 'nsu=' + NS + ';i=334',
   DemoModel_BinarySchema_SampleUnion: 'nsu=' + NS + ';i=50',
   DemoModel_BinarySchema_SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=53',
   DemoModel_BinarySchema_SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=56',
   DemoModel_BinarySchema_SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=59',
   DemoModel_BinarySchema_Person: 'nsu=' + NS + ';i=226',
   DemoModel_BinarySchema_Student: 'nsu=' + NS + ';i=229',
   DemoModel_XmlSchema: 'nsu=' + NS + ';i=9',
   DemoModel_XmlSchema_NamespaceUri: 'nsu=' + NS + ';i=11',
   DemoModel_XmlSchema_Deprecated: 'nsu=' + NS + ';i=66',
   DemoModel_XmlSchema_Vector: 'nsu=' + NS + ';i=12',
   DemoModel_XmlSchema_WorkOrderStatusType: 'nsu=' + NS + ';i=15',
   DemoModel_XmlSchema_WorkOrderType: 'nsu=' + NS + ';i=18',
   DemoModel_XmlSchema_ExtendedWorkOrderType: 'nsu=' + NS + ';i=328',
   DemoModel_XmlSchema_PenultimateWorkOrderType: 'nsu=' + NS + ';i=360',
   DemoModel_XmlSchema_FinalWorkOrderType: 'nsu=' + NS + ';i=338',
   DemoModel_XmlSchema_SampleUnion: 'nsu=' + NS + ';i=67',
   DemoModel_XmlSchema_SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=70',
   DemoModel_XmlSchema_SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=73',
   DemoModel_XmlSchema_SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=76',
   DemoModel_XmlSchema_Person: 'nsu=' + NS + ';i=234',
   DemoModel_XmlSchema_Student: 'nsu=' + NS + ';i=237',
});

export const VariableTypeIds = Object.freeze({
   RestrictedVariableType: 'nsu=' + NS + ';i=122',
   YellowType: 'nsu=' + NS + ';i=345',
});
