<!--
SPDX-FileCopyrightText: Copyright (c) 2026, OPC Federation AISBL
SPDX-License-Identifier: MIT
-->

<xs:schema targetNamespace="http://opcfoundation.org/UA/ECM/Types.xsd" elementFormDefault="qualified" xmlns:ua="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:tns="http://opcfoundation.org/UA/ECM/Types.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://opcfoundation.org/UA/2008/02/Types.xsd"/>
    <xs:simpleType name="MeasurementPeriodEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SlidingDemand_0"/>
            <xs:enumeration value="FixedBlockCompleted_1"/>
            <xs:enumeration value="FixedBlockInstantaneous_2"/>
            <xs:enumeration value="FixedBlockPredicted_3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="MeasurementPeriodEnum" type="tns:MeasurementPeriodEnum"/>
    <xs:complexType name="ListOfMeasurementPeriodEnum">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="MeasurementPeriodEnum" type="tns:MeasurementPeriodEnum" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfMeasurementPeriodEnum" type="tns:ListOfMeasurementPeriodEnum"/>
    <xs:complexType name="AcPeDataType">
        <xs:sequence>
            <xs:element minOccurs="0" name="L1" maxOccurs="1" type="xs:float"/>
            <xs:element minOccurs="0" name="L2" maxOccurs="1" type="xs:float"/>
            <xs:element minOccurs="0" name="L3" maxOccurs="1" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="AcPeDataType" type="tns:AcPeDataType"/>
    <xs:complexType name="ListOfAcPeDataType">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="AcPeDataType" type="tns:AcPeDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfAcPeDataType" type="tns:ListOfAcPeDataType"/>
    <xs:complexType name="AcPpDataType">
        <xs:sequence>
            <xs:element minOccurs="0" name="L1L2" maxOccurs="1" type="xs:float"/>
            <xs:element minOccurs="0" name="L2L3" maxOccurs="1" type="xs:float"/>
            <xs:element minOccurs="0" name="L3L1" maxOccurs="1" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="AcPpDataType" type="tns:AcPpDataType"/>
    <xs:complexType name="ListOfAcPpDataType">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="AcPpDataType" type="tns:AcPpDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfAcPpDataType" type="tns:ListOfAcPpDataType"/>
    <xs:complexType name="EnergyStateInformationDataType">
        <xs:sequence>
            <xs:element minOccurs="0" name="IDSource" maxOccurs="1" type="xs:unsignedByte"/>
            <xs:element minOccurs="0" name="IDDestination" maxOccurs="1" type="xs:unsignedByte"/>
            <xs:element minOccurs="0" name="RegularTimeToOperate" maxOccurs="1" type="xs:double"/>
            <xs:element minOccurs="0" name="ModePowerConsumption" maxOccurs="1" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="EnergyStateInformationDataType" type="tns:EnergyStateInformationDataType"/>
    <xs:complexType name="ListOfEnergyStateInformationDataType">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="EnergyStateInformationDataType" type="tns:EnergyStateInformationDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfEnergyStateInformationDataType" type="tns:ListOfEnergyStateInformationDataType"/>
    <xs:complexType name="MeasurementPeriodDataType">
        <xs:sequence>
            <xs:element minOccurs="0" name="Duration" maxOccurs="1" type="xs:double"/>
            <xs:element minOccurs="0" name="Definition" maxOccurs="1" type="tns:MeasurementPeriodEnum"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="MeasurementPeriodDataType" type="tns:MeasurementPeriodDataType"/>
    <xs:complexType name="ListOfMeasurementPeriodDataType">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="MeasurementPeriodDataType" type="tns:MeasurementPeriodDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfMeasurementPeriodDataType" type="tns:ListOfMeasurementPeriodDataType"/>
    <xs:complexType name="StandbyModeTransitionDataType">
        <xs:sequence>
            <xs:element minOccurs="0" name="IDDestination" maxOccurs="1" type="xs:unsignedByte"/>
            <xs:element minOccurs="0" name="CurrentTimeToDestination" maxOccurs="1" type="xs:double"/>
            <xs:element minOccurs="0" name="CurrentTimeToOperate" maxOccurs="1" type="xs:double"/>
            <xs:element minOccurs="0" name="EnergyConsumptionToDestination" maxOccurs="1" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="StandbyModeTransitionDataType" type="tns:StandbyModeTransitionDataType"/>
    <xs:complexType name="ListOfStandbyModeTransitionDataType">
        <xs:sequence>
            <xs:element nillable="true" minOccurs="0" name="StandbyModeTransitionDataType" type="tns:StandbyModeTransitionDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element nillable="true" name="ListOfStandbyModeTransitionDataType" type="tns:ListOfStandbyModeTransitionDataType"/>
</xs:schema>
