export const NS = 'urn:opcfoundation.org:2024-01:TestModel';

export class BrowseNames {
   static readonly Blue: string = 'Blue'
   static readonly EnumUnderscoreTest: string = 'EnumUnderscoreTest'
   static readonly ExtendedWorkOrderType: string = 'ExtendedWorkOrderType'
   static readonly FinalWorkOrderType: string = 'FinalWorkOrderType'
   static readonly HeaterStatus: string = 'HeaterStatus'
   static readonly Person: string = 'Person'
   static readonly Pink_Placeholder: string = '<Pink>'
   static readonly Red: string = 'Red'
   static readonly RestrictedObjectType: string = 'RestrictedObjectType'
   static readonly RestrictedVariableType: string = 'RestrictedVariableType'
   static readonly SampleStructureAllowSubtypes: string = 'SampleStructureAllowSubtypes'
   static readonly SampleStructureWithOptionalFields: string = 'SampleStructureWithOptionalFields'
   static readonly SampleUnion: string = 'SampleUnion'
   static readonly SampleUnionAllowSubtypes: string = 'SampleUnionAllowSubtypes'
   static readonly Seeker: string = 'Seeker'
   static readonly Student: string = 'Student'
   static readonly Test_Error: string = 'Test_Error'
   static readonly Test_ErrorComponent: string = 'Test_ErrorComponent'
   static readonly TestAbstractStructure: string = 'TestAbstractStructure'
   static readonly TestArrayStructure: string = 'TestArrayStructure'
   static readonly TestConcreteStructure: string = 'TestConcreteStructure'
   static readonly TestEnumeration: string = 'TestEnumeration'
   static readonly TestModel_BinarySchema: string = 'TestModel'
   static readonly TestModel_XmlSchema: string = 'TestModel'
   static readonly TestObject: string = 'TestObject'
   static readonly TestOptionalFields: string = 'TestOptionalFields'
   static readonly TestOptionSet: string = 'TestOptionSet'
   static readonly TestScalarStructure: string = 'TestScalarStructure'
   static readonly TestStructure: string = 'TestStructure'
   static readonly TestUnion: string = 'TestUnion'
   static readonly Vector: string = 'Vector'
   static readonly WithTwoDimensionalVariableType: string = 'WithTwoDimensionalVariableType'
   static readonly WorkOrderStatusType: string = 'WorkOrderStatusType'
   static readonly WorkOrderType: string = 'WorkOrderType'
   static readonly X: string = 'X'
   static readonly Y: string = 'Y'
   static readonly Yellow: string = 'Yellow'
   static readonly Z: string = 'Z'
}

export class DataTypeIds {
    static readonly TestAbstractStructure: string = 'nsu=' + NS + ';i=1'
    static readonly TestConcreteStructure: string = 'nsu=' + NS + ';i=2'
    static readonly TestUnion: string = 'nsu=' + NS + ';i=163'
    static readonly TestOptionalFields: string = 'nsu=' + NS + ';i=164'
    static readonly TestEnumeration: string = 'nsu=' + NS + ';i=3'
    static readonly TestOptionSet: string = 'nsu=' + NS + ';i=165'
    static readonly TestScalarStructure: string = 'nsu=' + NS + ';i=5'
    static readonly TestArrayStructure: string = 'nsu=' + NS + ';i=6'
    static readonly TestStructure: string = 'nsu=' + NS + ';i=167'
    static readonly EnumUnderscoreTest: string = 'nsu=' + NS + ';i=214'
    static readonly HeaterStatus: string = 'nsu=' + NS + ';i=242'
    static readonly Vector: string = 'nsu=' + NS + ';i=244'
    static readonly WorkOrderStatusType: string = 'nsu=' + NS + ';i=245'
    static readonly WorkOrderType: string = 'nsu=' + NS + ';i=246'
    static readonly ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=247'
    static readonly FinalWorkOrderType: string = 'nsu=' + NS + ';i=248'
    static readonly SampleUnion: string = 'nsu=' + NS + ';i=249'
    static readonly SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=250'
    static readonly SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=251'
    static readonly SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=252'
    static readonly Person: string = 'nsu=' + NS + ';i=255'
    static readonly Student: string = 'nsu=' + NS + ';i=256'
}

export class MethodIds {
    static readonly RestrictedObjectType_Blue: string = 'nsu=' + NS + ';i=232'
    static readonly TestObject_Blue: string = 'nsu=' + NS + ';i=239'
}

export class ObjectIds {
    static readonly Seeker: string = 'nsu=' + NS + ';i=195'
    static readonly TestObject: string = 'nsu=' + NS + ';i=233'
    static readonly Test_Error: string = 'nsu=' + NS + ';i=240'
    static readonly Test_ErrorComponent: string = 'nsu=' + NS + ';i=241'
    static readonly TestAbstractStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=8'
    static readonly TestConcreteStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=9'
    static readonly TestUnion_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=168'
    static readonly TestOptionalFields_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=169'
    static readonly TestScalarStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=10'
    static readonly TestArrayStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=11'
    static readonly TestStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=170'
    static readonly Vector_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=257'
    static readonly WorkOrderStatusType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=258'
    static readonly WorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=259'
    static readonly ExtendedWorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=260'
    static readonly FinalWorkOrderType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=261'
    static readonly SampleUnion_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=262'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=263'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=264'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=265'
    static readonly Person_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=266'
    static readonly Student_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=267'
    static readonly TestAbstractStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=32'
    static readonly TestConcreteStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=33'
    static readonly TestUnion_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=180'
    static readonly TestOptionalFields_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=181'
    static readonly TestScalarStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=34'
    static readonly TestArrayStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=35'
    static readonly TestStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=182'
    static readonly Vector_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=301'
    static readonly WorkOrderStatusType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=302'
    static readonly WorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=303'
    static readonly ExtendedWorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=304'
    static readonly FinalWorkOrderType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=305'
    static readonly SampleUnion_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=306'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=307'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=308'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=309'
    static readonly Person_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=310'
    static readonly Student_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=311'
    static readonly TestAbstractStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=56'
    static readonly TestConcreteStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=57'
    static readonly TestUnion_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=192'
    static readonly TestOptionalFields_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=193'
    static readonly TestScalarStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=58'
    static readonly TestArrayStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=59'
    static readonly TestStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=194'
    static readonly Vector_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=345'
    static readonly WorkOrderStatusType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=346'
    static readonly WorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=347'
    static readonly ExtendedWorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=348'
    static readonly FinalWorkOrderType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=349'
    static readonly SampleUnion_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=350'
    static readonly SampleStructureWithOptionalFields_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=351'
    static readonly SampleUnionAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=352'
    static readonly SampleStructureAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=353'
    static readonly Person_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=354'
    static readonly Student_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=355'
}

export class ObjectTypeIds {
    static readonly RestrictedObjectType: string = 'nsu=' + NS + ';i=221'
    static readonly WithTwoDimensionalVariableType: string = 'nsu=' + NS + ';i=253'
}

export class VariableIds {
    static readonly TestEnumeration_EnumValues: string = 'nsu=' + NS + ';i=4'
    static readonly TestOptionSet_OptionSetValues: string = 'nsu=' + NS + ';i=166'
    static readonly Seeker_Identities: string = 'nsu=' + NS + ';i=196'
    static readonly Seeker_AddIdentity_InputArguments: string = 'nsu=' + NS + ';i=203'
    static readonly Seeker_RemoveIdentity_InputArguments: string = 'nsu=' + NS + ';i=205'
    static readonly Seeker_AddApplication_InputArguments: string = 'nsu=' + NS + ';i=207'
    static readonly Seeker_RemoveApplication_InputArguments: string = 'nsu=' + NS + ';i=209'
    static readonly Seeker_AddEndpoint_InputArguments: string = 'nsu=' + NS + ';i=211'
    static readonly Seeker_RemoveEndpoint_InputArguments: string = 'nsu=' + NS + ';i=213'
    static readonly EnumUnderscoreTest_EnumValues: string = 'nsu=' + NS + ';i=215'
    static readonly RestrictedVariableType_Yellow: string = 'nsu=' + NS + ';i=217'
    static readonly RestrictedVariableType_X: string = 'nsu=' + NS + ';i=218'
    static readonly RestrictedVariableType_Y: string = 'nsu=' + NS + ';i=219'
    static readonly RestrictedVariableType_Z: string = 'nsu=' + NS + ';i=220'
    static readonly RestrictedObjectType_Red: string = 'nsu=' + NS + ';i=222'
    static readonly RestrictedObjectType_Red_Yellow: string = 'nsu=' + NS + ';i=223'
    static readonly RestrictedObjectType_Red_X: string = 'nsu=' + NS + ';i=224'
    static readonly RestrictedObjectType_Red_Y: string = 'nsu=' + NS + ';i=225'
    static readonly RestrictedObjectType_Red_Z: string = 'nsu=' + NS + ';i=226'
    static readonly RestrictedObjectType_Pink_Placeholder: string = 'nsu=' + NS + ';i=227'
    static readonly RestrictedObjectType_Pink_Placeholder_Yellow: string = 'nsu=' + NS + ';i=228'
    static readonly RestrictedObjectType_Pink_Placeholder_X: string = 'nsu=' + NS + ';i=229'
    static readonly RestrictedObjectType_Pink_Placeholder_Y: string = 'nsu=' + NS + ';i=230'
    static readonly RestrictedObjectType_Pink_Placeholder_Z: string = 'nsu=' + NS + ';i=231'
    static readonly TestObject_Red: string = 'nsu=' + NS + ';i=234'
    static readonly TestObject_Red_Yellow: string = 'nsu=' + NS + ';i=235'
    static readonly TestObject_Red_X: string = 'nsu=' + NS + ';i=236'
    static readonly TestObject_Red_Y: string = 'nsu=' + NS + ';i=237'
    static readonly TestObject_Red_Z: string = 'nsu=' + NS + ';i=238'
    static readonly HeaterStatus_EnumStrings: string = 'nsu=' + NS + ';i=243'
    static readonly WithTwoDimensionalVariableType_X: string = 'nsu=' + NS + ';i=254'
    static readonly TestModel_BinarySchema: string = 'nsu=' + NS + ';i=13'
    static readonly TestModel_BinarySchema_NamespaceUri: string = 'nsu=' + NS + ';i=15'
    static readonly TestModel_BinarySchema_Deprecated: string = 'nsu=' + NS + ';i=16'
    static readonly TestModel_BinarySchema_TestAbstractStructure: string = 'nsu=' + NS + ';i=17'
    static readonly TestModel_BinarySchema_TestConcreteStructure: string = 'nsu=' + NS + ';i=20'
    static readonly TestModel_BinarySchema_TestUnion: string = 'nsu=' + NS + ';i=171'
    static readonly TestModel_BinarySchema_TestOptionalFields: string = 'nsu=' + NS + ';i=174'
    static readonly TestModel_BinarySchema_TestScalarStructure: string = 'nsu=' + NS + ';i=23'
    static readonly TestModel_BinarySchema_TestArrayStructure: string = 'nsu=' + NS + ';i=26'
    static readonly TestModel_BinarySchema_TestStructure: string = 'nsu=' + NS + ';i=177'
    static readonly TestModel_BinarySchema_Vector: string = 'nsu=' + NS + ';i=268'
    static readonly TestModel_BinarySchema_WorkOrderStatusType: string = 'nsu=' + NS + ';i=271'
    static readonly TestModel_BinarySchema_WorkOrderType: string = 'nsu=' + NS + ';i=274'
    static readonly TestModel_BinarySchema_ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=277'
    static readonly TestModel_BinarySchema_FinalWorkOrderType: string = 'nsu=' + NS + ';i=280'
    static readonly TestModel_BinarySchema_SampleUnion: string = 'nsu=' + NS + ';i=283'
    static readonly TestModel_BinarySchema_SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=286'
    static readonly TestModel_BinarySchema_SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=289'
    static readonly TestModel_BinarySchema_SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=292'
    static readonly TestModel_BinarySchema_Person: string = 'nsu=' + NS + ';i=295'
    static readonly TestModel_BinarySchema_Student: string = 'nsu=' + NS + ';i=298'
    static readonly TestModel_XmlSchema: string = 'nsu=' + NS + ';i=37'
    static readonly TestModel_XmlSchema_NamespaceUri: string = 'nsu=' + NS + ';i=39'
    static readonly TestModel_XmlSchema_Deprecated: string = 'nsu=' + NS + ';i=40'
    static readonly TestModel_XmlSchema_TestAbstractStructure: string = 'nsu=' + NS + ';i=41'
    static readonly TestModel_XmlSchema_TestConcreteStructure: string = 'nsu=' + NS + ';i=44'
    static readonly TestModel_XmlSchema_TestUnion: string = 'nsu=' + NS + ';i=183'
    static readonly TestModel_XmlSchema_TestOptionalFields: string = 'nsu=' + NS + ';i=186'
    static readonly TestModel_XmlSchema_TestScalarStructure: string = 'nsu=' + NS + ';i=47'
    static readonly TestModel_XmlSchema_TestArrayStructure: string = 'nsu=' + NS + ';i=50'
    static readonly TestModel_XmlSchema_TestStructure: string = 'nsu=' + NS + ';i=189'
    static readonly TestModel_XmlSchema_Vector: string = 'nsu=' + NS + ';i=312'
    static readonly TestModel_XmlSchema_WorkOrderStatusType: string = 'nsu=' + NS + ';i=315'
    static readonly TestModel_XmlSchema_WorkOrderType: string = 'nsu=' + NS + ';i=318'
    static readonly TestModel_XmlSchema_ExtendedWorkOrderType: string = 'nsu=' + NS + ';i=321'
    static readonly TestModel_XmlSchema_FinalWorkOrderType: string = 'nsu=' + NS + ';i=324'
    static readonly TestModel_XmlSchema_SampleUnion: string = 'nsu=' + NS + ';i=327'
    static readonly TestModel_XmlSchema_SampleStructureWithOptionalFields: string = 'nsu=' + NS + ';i=330'
    static readonly TestModel_XmlSchema_SampleUnionAllowSubtypes: string = 'nsu=' + NS + ';i=333'
    static readonly TestModel_XmlSchema_SampleStructureAllowSubtypes: string = 'nsu=' + NS + ';i=336'
    static readonly TestModel_XmlSchema_Person: string = 'nsu=' + NS + ';i=339'
    static readonly TestModel_XmlSchema_Student: string = 'nsu=' + NS + ';i=342'
}

export class VariableTypeIds {
    static readonly RestrictedVariableType: string = 'nsu=' + NS + ';i=216'
}
