export const NS = 'urn:opcfoundation.org:2024-01:TestModel';

export const BrowseNames = Object.freeze({
   Blue: 'Blue',
   EnumUnderscoreTest: 'EnumUnderscoreTest',
   ExtendedWorkOrderType: 'ExtendedWorkOrderType',
   FinalWorkOrderType: 'FinalWorkOrderType',
   HeaterStatus: 'HeaterStatus',
   Person: 'Person',
   Pink_Placeholder: '<Pink>',
   Red: 'Red',
   RestrictedObjectType: 'RestrictedObjectType',
   RestrictedVariableType: 'RestrictedVariableType',
   SampleStructureAllowSubtypes: 'SampleStructureAllowSubtypes',
   SampleStructureWithOptionalFields: 'SampleStructureWithOptionalFields',
   SampleUnion: 'SampleUnion',
   SampleUnionAllowSubtypes: 'SampleUnionAllowSubtypes',
   Seeker: 'Seeker',
   Student: 'Student',
   Test_Error: 'Test_Error',
   Test_ErrorComponent: 'Test_ErrorComponent',
   TestAbstractStructure: 'TestAbstractStructure',
   TestArrayStructure: 'TestArrayStructure',
   TestConcreteStructure: 'TestConcreteStructure',
   TestEnumeration: 'TestEnumeration',
   TestModel_BinarySchema: 'TestModel',
   TestModel_XmlSchema: 'TestModel',
   TestObject: 'TestObject',
   TestOptionalFields: 'TestOptionalFields',
   TestOptionSet: 'TestOptionSet',
   TestScalarStructure: 'TestScalarStructure',
   TestStructure: 'TestStructure',
   TestUnion: 'TestUnion',
   Vector: 'Vector',
   WithTwoDimensionalVariableType: 'WithTwoDimensionalVariableType',
   WorkOrderStatusType: 'WorkOrderStatusType',
   WorkOrderType: 'WorkOrderType',
   X: 'X',
   Y: 'Y',
   Yellow: 'Yellow',
   Z: 'Z',
});

export const DataTypeIds = Object.freeze({
   TestAbstractStructure: 'nsu=' + NS + ';i=1',
   TestConcreteStructure: 'nsu=' + NS + ';i=2',
   TestUnion: 'nsu=' + NS + ';i=163',
   TestOptionalFields: 'nsu=' + NS + ';i=164',
   TestEnumeration: 'nsu=' + NS + ';i=3',
   TestOptionSet: 'nsu=' + NS + ';i=165',
   TestScalarStructure: 'nsu=' + NS + ';i=5',
   TestArrayStructure: 'nsu=' + NS + ';i=6',
   TestStructure: 'nsu=' + NS + ';i=167',
   EnumUnderscoreTest: 'nsu=' + NS + ';i=214',
   HeaterStatus: 'nsu=' + NS + ';i=242',
   Vector: 'nsu=' + NS + ';i=244',
   WorkOrderStatusType: 'nsu=' + NS + ';i=245',
   WorkOrderType: 'nsu=' + NS + ';i=246',
   ExtendedWorkOrderType: 'nsu=' + NS + ';i=247',
   FinalWorkOrderType: 'nsu=' + NS + ';i=248',
   SampleUnion: 'nsu=' + NS + ';i=249',
   SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=250',
   SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=251',
   SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=252',
   Person: 'nsu=' + NS + ';i=255',
   Student: 'nsu=' + NS + ';i=256',
});

export const MethodIds = Object.freeze({
   RestrictedObjectType_Blue: 'nsu=' + NS + ';i=232',
   TestObject_Blue: 'nsu=' + NS + ';i=239',
});

export const ObjectIds = Object.freeze({
   Seeker: 'nsu=' + NS + ';i=195',
   TestObject: 'nsu=' + NS + ';i=233',
   Test_Error: 'nsu=' + NS + ';i=240',
   Test_ErrorComponent: 'nsu=' + NS + ';i=241',
   TestAbstractStructure_Encoding_DefaultBinary: 'nsu=' + NS + ';i=8',
   TestConcreteStructure_Encoding_DefaultBinary: 'nsu=' + NS + ';i=9',
   TestUnion_Encoding_DefaultBinary: 'nsu=' + NS + ';i=168',
   TestOptionalFields_Encoding_DefaultBinary: 'nsu=' + NS + ';i=169',
   TestScalarStructure_Encoding_DefaultBinary: 'nsu=' + NS + ';i=10',
   TestArrayStructure_Encoding_DefaultBinary: 'nsu=' + NS + ';i=11',
   TestStructure_Encoding_DefaultBinary: 'nsu=' + NS + ';i=170',
   Vector_Encoding_DefaultBinary: 'nsu=' + NS + ';i=257',
   WorkOrderStatusType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=258',
   WorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=259',
   ExtendedWorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=260',
   FinalWorkOrderType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=261',
   SampleUnion_Encoding_DefaultBinary: 'nsu=' + NS + ';i=262',
   SampleStructureWithOptionalFields_Encoding_DefaultBinary: 'nsu=' + NS + ';i=263',
   SampleUnionAllowSubtypes_Encoding_DefaultBinary: 'nsu=' + NS + ';i=264',
   SampleStructureAllowSubtypes_Encoding_DefaultBinary: 'nsu=' + NS + ';i=265',
   Person_Encoding_DefaultBinary: 'nsu=' + NS + ';i=266',
   Student_Encoding_DefaultBinary: 'nsu=' + NS + ';i=267',
   TestAbstractStructure_Encoding_DefaultXml: 'nsu=' + NS + ';i=32',
   TestConcreteStructure_Encoding_DefaultXml: 'nsu=' + NS + ';i=33',
   TestUnion_Encoding_DefaultXml: 'nsu=' + NS + ';i=180',
   TestOptionalFields_Encoding_DefaultXml: 'nsu=' + NS + ';i=181',
   TestScalarStructure_Encoding_DefaultXml: 'nsu=' + NS + ';i=34',
   TestArrayStructure_Encoding_DefaultXml: 'nsu=' + NS + ';i=35',
   TestStructure_Encoding_DefaultXml: 'nsu=' + NS + ';i=182',
   Vector_Encoding_DefaultXml: 'nsu=' + NS + ';i=301',
   WorkOrderStatusType_Encoding_DefaultXml: 'nsu=' + NS + ';i=302',
   WorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=303',
   ExtendedWorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=304',
   FinalWorkOrderType_Encoding_DefaultXml: 'nsu=' + NS + ';i=305',
   SampleUnion_Encoding_DefaultXml: 'nsu=' + NS + ';i=306',
   SampleStructureWithOptionalFields_Encoding_DefaultXml: 'nsu=' + NS + ';i=307',
   SampleUnionAllowSubtypes_Encoding_DefaultXml: 'nsu=' + NS + ';i=308',
   SampleStructureAllowSubtypes_Encoding_DefaultXml: 'nsu=' + NS + ';i=309',
   Person_Encoding_DefaultXml: 'nsu=' + NS + ';i=310',
   Student_Encoding_DefaultXml: 'nsu=' + NS + ';i=311',
   TestAbstractStructure_Encoding_DefaultJson: 'nsu=' + NS + ';i=56',
   TestConcreteStructure_Encoding_DefaultJson: 'nsu=' + NS + ';i=57',
   TestUnion_Encoding_DefaultJson: 'nsu=' + NS + ';i=192',
   TestOptionalFields_Encoding_DefaultJson: 'nsu=' + NS + ';i=193',
   TestScalarStructure_Encoding_DefaultJson: 'nsu=' + NS + ';i=58',
   TestArrayStructure_Encoding_DefaultJson: 'nsu=' + NS + ';i=59',
   TestStructure_Encoding_DefaultJson: 'nsu=' + NS + ';i=194',
   Vector_Encoding_DefaultJson: 'nsu=' + NS + ';i=345',
   WorkOrderStatusType_Encoding_DefaultJson: 'nsu=' + NS + ';i=346',
   WorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=347',
   ExtendedWorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=348',
   FinalWorkOrderType_Encoding_DefaultJson: 'nsu=' + NS + ';i=349',
   SampleUnion_Encoding_DefaultJson: 'nsu=' + NS + ';i=350',
   SampleStructureWithOptionalFields_Encoding_DefaultJson: 'nsu=' + NS + ';i=351',
   SampleUnionAllowSubtypes_Encoding_DefaultJson: 'nsu=' + NS + ';i=352',
   SampleStructureAllowSubtypes_Encoding_DefaultJson: 'nsu=' + NS + ';i=353',
   Person_Encoding_DefaultJson: 'nsu=' + NS + ';i=354',
   Student_Encoding_DefaultJson: 'nsu=' + NS + ';i=355',
});

export const ObjectTypeIds = Object.freeze({
   RestrictedObjectType: 'nsu=' + NS + ';i=221',
   WithTwoDimensionalVariableType: 'nsu=' + NS + ';i=253',
});

export const VariableIds = Object.freeze({
   TestEnumeration_EnumValues: 'nsu=' + NS + ';i=4',
   TestOptionSet_OptionSetValues: 'nsu=' + NS + ';i=166',
   Seeker_Identities: 'nsu=' + NS + ';i=196',
   Seeker_AddIdentity_InputArguments: 'nsu=' + NS + ';i=203',
   Seeker_RemoveIdentity_InputArguments: 'nsu=' + NS + ';i=205',
   Seeker_AddApplication_InputArguments: 'nsu=' + NS + ';i=207',
   Seeker_RemoveApplication_InputArguments: 'nsu=' + NS + ';i=209',
   Seeker_AddEndpoint_InputArguments: 'nsu=' + NS + ';i=211',
   Seeker_RemoveEndpoint_InputArguments: 'nsu=' + NS + ';i=213',
   EnumUnderscoreTest_EnumValues: 'nsu=' + NS + ';i=215',
   RestrictedVariableType_Yellow: 'nsu=' + NS + ';i=217',
   RestrictedVariableType_X: 'nsu=' + NS + ';i=218',
   RestrictedVariableType_Y: 'nsu=' + NS + ';i=219',
   RestrictedVariableType_Z: 'nsu=' + NS + ';i=220',
   RestrictedObjectType_Red: 'nsu=' + NS + ';i=222',
   RestrictedObjectType_Red_Yellow: 'nsu=' + NS + ';i=223',
   RestrictedObjectType_Red_X: 'nsu=' + NS + ';i=224',
   RestrictedObjectType_Red_Y: 'nsu=' + NS + ';i=225',
   RestrictedObjectType_Red_Z: 'nsu=' + NS + ';i=226',
   RestrictedObjectType_Pink_Placeholder: 'nsu=' + NS + ';i=227',
   RestrictedObjectType_Pink_Placeholder_Yellow: 'nsu=' + NS + ';i=228',
   RestrictedObjectType_Pink_Placeholder_X: 'nsu=' + NS + ';i=229',
   RestrictedObjectType_Pink_Placeholder_Y: 'nsu=' + NS + ';i=230',
   RestrictedObjectType_Pink_Placeholder_Z: 'nsu=' + NS + ';i=231',
   TestObject_Red: 'nsu=' + NS + ';i=234',
   TestObject_Red_Yellow: 'nsu=' + NS + ';i=235',
   TestObject_Red_X: 'nsu=' + NS + ';i=236',
   TestObject_Red_Y: 'nsu=' + NS + ';i=237',
   TestObject_Red_Z: 'nsu=' + NS + ';i=238',
   HeaterStatus_EnumStrings: 'nsu=' + NS + ';i=243',
   WithTwoDimensionalVariableType_X: 'nsu=' + NS + ';i=254',
   TestModel_BinarySchema: 'nsu=' + NS + ';i=13',
   TestModel_BinarySchema_NamespaceUri: 'nsu=' + NS + ';i=15',
   TestModel_BinarySchema_Deprecated: 'nsu=' + NS + ';i=16',
   TestModel_BinarySchema_TestAbstractStructure: 'nsu=' + NS + ';i=17',
   TestModel_BinarySchema_TestConcreteStructure: 'nsu=' + NS + ';i=20',
   TestModel_BinarySchema_TestUnion: 'nsu=' + NS + ';i=171',
   TestModel_BinarySchema_TestOptionalFields: 'nsu=' + NS + ';i=174',
   TestModel_BinarySchema_TestScalarStructure: 'nsu=' + NS + ';i=23',
   TestModel_BinarySchema_TestArrayStructure: 'nsu=' + NS + ';i=26',
   TestModel_BinarySchema_TestStructure: 'nsu=' + NS + ';i=177',
   TestModel_BinarySchema_Vector: 'nsu=' + NS + ';i=268',
   TestModel_BinarySchema_WorkOrderStatusType: 'nsu=' + NS + ';i=271',
   TestModel_BinarySchema_WorkOrderType: 'nsu=' + NS + ';i=274',
   TestModel_BinarySchema_ExtendedWorkOrderType: 'nsu=' + NS + ';i=277',
   TestModel_BinarySchema_FinalWorkOrderType: 'nsu=' + NS + ';i=280',
   TestModel_BinarySchema_SampleUnion: 'nsu=' + NS + ';i=283',
   TestModel_BinarySchema_SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=286',
   TestModel_BinarySchema_SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=289',
   TestModel_BinarySchema_SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=292',
   TestModel_BinarySchema_Person: 'nsu=' + NS + ';i=295',
   TestModel_BinarySchema_Student: 'nsu=' + NS + ';i=298',
   TestModel_XmlSchema: 'nsu=' + NS + ';i=37',
   TestModel_XmlSchema_NamespaceUri: 'nsu=' + NS + ';i=39',
   TestModel_XmlSchema_Deprecated: 'nsu=' + NS + ';i=40',
   TestModel_XmlSchema_TestAbstractStructure: 'nsu=' + NS + ';i=41',
   TestModel_XmlSchema_TestConcreteStructure: 'nsu=' + NS + ';i=44',
   TestModel_XmlSchema_TestUnion: 'nsu=' + NS + ';i=183',
   TestModel_XmlSchema_TestOptionalFields: 'nsu=' + NS + ';i=186',
   TestModel_XmlSchema_TestScalarStructure: 'nsu=' + NS + ';i=47',
   TestModel_XmlSchema_TestArrayStructure: 'nsu=' + NS + ';i=50',
   TestModel_XmlSchema_TestStructure: 'nsu=' + NS + ';i=189',
   TestModel_XmlSchema_Vector: 'nsu=' + NS + ';i=312',
   TestModel_XmlSchema_WorkOrderStatusType: 'nsu=' + NS + ';i=315',
   TestModel_XmlSchema_WorkOrderType: 'nsu=' + NS + ';i=318',
   TestModel_XmlSchema_ExtendedWorkOrderType: 'nsu=' + NS + ';i=321',
   TestModel_XmlSchema_FinalWorkOrderType: 'nsu=' + NS + ';i=324',
   TestModel_XmlSchema_SampleUnion: 'nsu=' + NS + ';i=327',
   TestModel_XmlSchema_SampleStructureWithOptionalFields: 'nsu=' + NS + ';i=330',
   TestModel_XmlSchema_SampleUnionAllowSubtypes: 'nsu=' + NS + ';i=333',
   TestModel_XmlSchema_SampleStructureAllowSubtypes: 'nsu=' + NS + ';i=336',
   TestModel_XmlSchema_Person: 'nsu=' + NS + ';i=339',
   TestModel_XmlSchema_Student: 'nsu=' + NS + ';i=342',
});

export const VariableTypeIds = Object.freeze({
   RestrictedVariableType: 'nsu=' + NS + ';i=216',
});
